DROP TABLE REGISTER;
CREATE TABLE REGISTER 
(
  ID NUMBER(4, 0) NOT NULL 
, NAME VARCHAR2(100 BYTE) 
, PASSWORD VARCHAR2(100 BYTE) 
, EMAIL VARCHAR2(100 BYTE) 
, SEX VARCHAR2(100 BYTE) 
, COUNTRY VARCHAR2(100 BYTE) 
, CONSTRAINT REGISTER_PK2 PRIMARY KEY (ID)
);
GO;
INSERT INTO REGISTER VALUES(1, '이순신', '1234', 'lee@gmail.com', 'male', 'Korea');
INSERT INTO REGISTER VALUES(2, '홍길동', '1234', 'hong@gmail.com', 'female', 'English');
INSERT INTO REGISTER VALUES(3, '강감찬', '1234', 'kang@gmail.com', 'male', 'Korea');
INSERT INTO REGISTER VALUES(4, '권율', '1234', 'kyun@gmail.com', 'female', 'Korea');